name: crud
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  date_field: ^3.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
